export const GET_DEFAULT_VIDEOGAMES = "GET_DEFAULT_VIDEOGAMES"

export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME"

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"

export const SET_ITEMS_PER_PAGE = "SET_ITEMS_PER_PAGE"

export const RENDER_VIDEOGAMES = "RENDER_VIDEOGAMES" 

export const SEARCH_VIDEOGAME_BY_NAME = "SEARCH_VIDEOGAME_BY_NAME"

export const GET_GENRES = "GET_GENRES"

export const GET_PLATFORMS = "GET_PLATFORMS"